# MODULE 3 â€” Pandas : Manipulation des Donnees

Dans les modules precedents, on a appris Python et NumPy.

Maintenant on decouvre **Pandas** â€” la bibliotheque la plus utilisee en data science !

Pandas permet de travailler avec des **tableaux de donnees** (comme des feuilles Excel) directement en Python.

Dans ce module, tu vas apprendre :
- Charger un fichier CSV avec `pd.read_csv()`
- Explorer un dataset (head, tail, info, describe, shape)
- Selectionner des colonnes
- Filtrer des lignes selon des conditions
- Trier les donnees
- Grouper et agreger les donnees
- Fusionner des tableaux
- Sauvegarder en CSV

---
## PARTIE 1 â€” Importer Pandas

### Qu'est-ce que Pandas ?

**Pandas** est une bibliotheque Python qui permet de manipuler des **tableaux de donnees**.

Imagine un tableau Excel ultra-puissant que tu peux controler avec du code Python.

Ce tableau s'appelle un **DataFrame** en Pandas.

```
          id   date       client        age   ville    total
       +----+----------+------------+-----+--------+--------+
    0  |  1 | 2024-01  | Alice M.   |  35 | Paris  | 1250.5 |
    1  |  2 | 2024-02  | Bob D.     |  28 | Lyon   |  890.0 |
    2  |  3 | 2024-03  | Clara T.   |  42 | Nice   | 2100.0 |
       +----+----------+------------+-----+--------+--------+
index ->  ^     colonne  ->  colonnes ->  colonnes -> colonne
```

- Les **lignes** = les observations (ici, les ventes)
- Les **colonnes** = les variables (ici, les informations sur chaque vente)
- L'**index** = le numero de chaque ligne (commence a 0)

In [1]:
# On importe pandas avec le surnom "pd"
# "as pd" veut dire : appelle pandas "pd" pour aller plus vite a ecrire
import pandas as pd

print("Pandas est pret !")
print("Version de Pandas :", pd.__version__)

Pandas est pret !
Version de Pandas : 2.3.3

---
## PARTIE 2 â€” Charger un fichier CSV

### pd.read_csv() : la porte d'entree des donnees

`pd.read_csv()` lit un fichier CSV et le transforme en **DataFrame** (tableau Pandas).

C'est comme "ouvrir" un fichier Excel, mais en Python.

In [2]:
# On charge le fichier CSV des ventes dans un DataFrame
# pd.read_csv() lit le fichier et cree un tableau Pandas
# On appelle ce tableau "df" (abrÃ©viation de DataFrame)
df = pd.read_csv("ventes_koryxa.csv", encoding="utf-8")

print("Fichier charge avec succes !")
print("Type :", type(df))  # affiche <class 'pandas.core.frame.DataFrame'>

Fichier charge avec succes !
Type : <class 'pandas.core.frame.DataFrame'>

---
## PARTIE 3 â€” Explorer le DataFrame

### Les commandes d'exploration

Quand on charge un nouveau dataset, la premiere chose a faire c'est l'**explorer** : regarder sa forme, ses colonnes, ses valeurs.

Voici les commandes indispensables :

In [3]:
# df.head() affiche les 5 premieres lignes du tableau
# C'est comme regarder les premieres pages d'un livre
# Tres utile pour avoir un apercu rapide des donnees
print("=== Les 5 premieres lignes ===")
df.head()

=== Les 5 premieres lignes ===

,id,date,client,age,ville,region,produit,categorie,quantite,prix_unitaire,total,paiement,satisfaction
0,1,2024-10-18,Karim Benali,65.0,paris,Île-de-France,Casque Audio,Audio,2,279.50,559.00,Mobile Money,1.0
1,2,2024-07-18,Omar Sy,23.0,Casablanca,Auvergne-Rhône-Alpes,Imprimante,Informatique,4,52.66,210.64,Espèces,2.0
2,3,2024-11-12,Julia Santos,NaN,Paris,NaN,Écran 4K,Informatique,5,512.13,2560.65,Virement,5.0
3,4,2024-02-05,Nina Rousseau,31.0,Paris,PACA,Disque SSD,Stockage,3,344.28,1032.84,Carte Bancaire,3.0
4,5,2024-02-18,Georges Mbeki,20.0,paris,Belgique,Webcam HD,Périphérique,5,328.46,1642.30,PayPal,4.0

In [4]:
# df.tail() affiche les 5 dernieres lignes
# Utile pour voir si les dernieres donnees sont correctes
print("=== Les 5 dernieres lignes ===")
df.tail()

=== Les 5 dernieres lignes ===

,id,date,client,age,ville,region,produit,categorie,quantite,prix_unitaire,total,paiement,satisfaction
95,96,2024-03-18,Omar Sy,57.0,Dakar,Auvergne-Rhône-Alpes,Tapis de Souris,Accessoire,3,997.84,2993.52,PayPal,3.0
96,97,2024-02-05,Hana Yamada,33.0,Paris,Auvergne-Rhône-Alpes,Webcam HD,Périphérique,3,298.75,896.25,Carte Bancaire,5.0
97,98,2024-02-18,Clara Ndiaye,45.0,Montréal,Afrique du Nord,Clavier Mécanique,Périphérique,4,668.74,2674.96,Carte Bancaire,5.0
98,99,2024-07-05,Alice Martin,19.0,Lyon,Canada,Disque SSD,Stockage,5,1136.08,5680.40,carte bancaire,5.0
99,100,2024-03-25,Bob Dupont,62.0,Tunis,Afrique de l'Ouest,Webcam HD,Périphérique,1,895.31,895.31,Espèces,2.0

In [5]:
# df.shape donne la taille du tableau : (nombre de lignes, nombre de colonnes)
# C'est comme demander "c'est grand comment ce tableau ?"
lignes, colonnes = df.shape  # on separe en deux variables
print(f"Le tableau a {lignes} lignes et {colonnes} colonnes")

Le tableau a 100 lignes et 13 colonnes

In [6]:
# df.info() donne des informations sur chaque colonne :
# - le nom de la colonne
# - le nombre de valeurs non-nulles (non-vides)
# - le type de donnees (int, float, object=texte)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             100 non-null    int64
 1   date           100 non-null    object
 2   client         100 non-null    object
 3   age            95 non-null     float64
 4   ville          100 non-null    object
 5   region         78 non-null     object
 6   produit        100 non-null    object
 7   categorie      100 non-null    object
 8   quantite       100 non-null    int64
 9   prix_unitaire  100 non-null    float64
 10  total          100 non-null    float64
 11  paiement       97 non-null     object
 12  satisfaction   94 non-null     float64
dtypes: float64(4), int64(2), object(7)
memory usage: 10.3+ KB

In [7]:
# df.describe() calcule les statistiques de base pour chaque colonne numerique
# count = nombre de valeurs, mean = moyenne, std = ecart-type
# min = minimum, 25% = premier quartile, 50% = mediane, 75% = troisieme quartile
# max = maximum
df.describe()

,id,age,quantite,prix_unitaire,total,satisfaction
count,100.000000,95.000000,100.000000,100.000000,100.000000,94.000000
mean,50.500000,41.568421,4.880000,867.451600,4172.620600,3.106383
std,29.011492,13.995176,11.953851,1337.730353,12124.920591,1.432856
min,1.000000,18.000000,1.000000,27.030000,135.150000,1.000000
25%,25.750000,31.000000,2.000000,344.880000,894.540000,2.000000
50%,50.500000,43.000000,3.000000,670.360000,1784.170000,3.000000
75%,75.250000,53.500000,4.250000,972.135000,2916.705000,4.000000
max,100.000000,65.000000,97.000000,9301.340000,93668.050000,5.000000

---
## PARTIE 4 â€” Selectionner des colonnes

### Acceder a une seule colonne

Pour acceder a une colonne, on ecrit le nom du DataFrame suivi du **nom de la colonne** entre crochets et guillemets.

C'est comme dire : "Dans le tableau, donne-moi seulement la colonne des prix"

In [8]:
# Selectionner une seule colonne avec df["nom_colonne"]
# On obtient une "Series" Pandas (une colonne)
colonne_total = df["total"]
print("Type :", type(colonne_total))   # Series = une colonne
print(colonne_total.head(5))           # affiche les 5 premiers valeurs

Type : <class 'pandas.core.series.Series'>
0     559.00
1     210.64
2    2560.65
3    1032.84
4    1642.30
Name: total, dtype: float64

In [9]:
# Selectionner plusieurs colonnes avec df[["col1", "col2"]]
# On met une liste de noms de colonnes (deux crochets !!)
selection = df[["client", "produit", "total"]]
print("Selection de 3 colonnes :")
print(selection.head(5))  # affiche les 5 premieres lignes

Selection de 3 colonnes :
          client       produit    total
0   Karim Benali  Casque Audio   559.00
1        Omar Sy    Imprimante   210.64
2   Julia Santos      Écran 4K  2560.65
3  Nina Rousseau    Disque SSD  1032.84
4  Georges Mbeki     Webcam HD  1642.30

---
## PARTIE 5 â€” iloc et loc : selectionner par position ou par etiquette

### Deux methodes de selection

- **`iloc`** = selection par **position numerique** (comme les index Python)
- **`loc`** = selection par **etiquette** (nom de ligne ou condition)

Pense a :
- `iloc` = "I look at position **i**" (je regarde a la position i)
- `loc` = "I **loc**ate by label" (je localise par etiquette/nom)

In [10]:
# iloc : selection par numero de position
# df.iloc[ligne, colonne] -> indices numeriques
print("=== Selection avec iloc ===")
print("Ligne 0, toutes colonnes :")
print(df.iloc[0])      # toute la premiere ligne

=== Selection avec iloc ===
Ligne 0, toutes colonnes :
id                           1
date                2024-10-18
client            Karim Benali
age                       65.0
ville                    paris
region           Île-de-France
produit           Casque Audio
categorie                Audio
quantite                     2
prix_unitaire            279.5
total                    559.0
paiement          Mobile Money
satisfaction               1.0
Name: 0, dtype: object

In [11]:
# iloc avec des plages
# df.iloc[0:3, 0:4] -> lignes 0,1,2 et colonnes 0,1,2,3
print("Lignes 0 a 2, colonnes 0 a 3 :")
print(df.iloc[0:3, 0:4])

Lignes 0 a 2, colonnes 0 a 3 :
   id        date        client   age
0   1  2024-10-18  Karim Benali  65.0
1   2  2024-07-18       Omar Sy  23.0
2   3  2024-11-12  Julia Santos   NaN

In [12]:
# loc : selection par nom de colonne
# df.loc[condition, "nom_colonne"]
print("=== Selection avec loc ===")
print("Premiere ligne, colonnes client et total :")
print(df.loc[0, ["client", "total"]])

=== Selection avec loc ===
Premiere ligne, colonnes client et total :
client    Karim Benali
total            559.0
Name: 0, dtype: object

---
## PARTIE 6 â€” Filtrer les lignes

### Selectionner les lignes selon une condition

C'est comme faire une recherche dans Excel : "montre-moi seulement les ventes de Paris".

En Pandas, on ecrit la condition entre crochets apres le nom du DataFrame.

In [13]:
# Filtrer les ventes de Paris seulement
# df["ville"] == "Paris" cree un tableau True/False
# On garde seulement les lignes ou c'est True
ventes_paris = df[df["ville"] == "Paris"]

print(f"Nombre de ventes a Paris : {len(ventes_paris)}")
print(ventes_paris[["client", "ville", "produit", "total"]].head(5))

Nombre de ventes a Paris : 11
            client  ville            produit     total
2     Julia Santos  Paris           Écran 4K   2560.65
3    Nina Rousseau  Paris         Disque SSD   1032.84
13  Mohamed Traoré  Paris  Clavier Mécanique  73427.97
18     Hana Yamada  Paris          Webcam HD    896.25
23         Omar Sy  Paris    Souris Sans Fil   1485.20

In [14]:
# Filtrer les ventes avec un total superieur a 1000 euros
grandes_ventes = df[df["total"] > 1000]

print(f"Nombre de grandes ventes (>1000 euros) : {len(grandes_ventes)}")
print(grandes_ventes[["client", "produit", "total"]].head(5))

Nombre de grandes ventes (>1000 euros) : 69
          client          produit     total
2   Julia Santos         Écran 4K   2560.65
3  Nina Rousseau       Disque SSD   1032.84
4  Georges Mbeki        Webcam HD   1642.30
5        Omar Sy  Tapis de Souris   2993.52
6    Laura Petit         Écran 4K  27827.19

In [15]:
# Combiner deux conditions avec & (ET) ou | (OU)
# & = les deux conditions doivent etre vraies
# Ventes de Paris ET avec total > 500
ventes_paris_grandes = df[(df["ville"] == "Paris") & (df["total"] > 500)]

print(f"Ventes a Paris avec total > 500 euros : {len(ventes_paris_grandes)}")

Ventes a Paris avec total > 500 euros : 11

---
## PARTIE 7 â€” Trier les donnees

### sort_values() : trier le tableau

`sort_values()` permet de trier le tableau selon une (ou plusieurs) colonnes.

C'est comme cliquer sur l'en-tete d'une colonne dans Excel pour trier.

In [16]:
# Trier par total de vente, du plus grand au plus petit
# ascending=False = ordre decroissant (grand -> petit)
df_trie = df.sort_values("total", ascending=False)

print("Top 5 des plus grandes ventes :")
print(df_trie[["client", "produit", "total"]].head(5))

Top 5 des plus grandes ventes :
            client            produit     total
46   Georges Mbeki          Webcam HD  93668.05
13  Mohamed Traoré  Clavier Mécanique  73427.97
6      Laura Petit           Écran 4K  27827.19
22    Alice Martin           Écran 4K  26774.45
60     Hana Yamada  Clavier Mécanique   9301.34

In [17]:
# Trier par plusieurs colonnes
# D'abord par ville (A->Z), puis par total (grand->petit)
df_trie2 = df.sort_values(["ville", "total"], ascending=[True, False])

print("Ventes triees par ville puis par total decroissant :")
print(df_trie2[["ville", "client", "total"]].head(8))

Ventes triees par ville puis par total decroissant :
      ville         client    total
14  Abidjan   Julia Santos  5175.10
89  Abidjan    Laura Petit  3611.00
85  Abidjan  Georges Mbeki  3121.56
69  Abidjan     David Osei  2361.96
75  Abidjan   Clara Ndiaye  1132.14
27  Abidjan   Ibrahim Koné   690.16
36  Abidjan   Emma Leclerc   558.07
19  Abidjan    Laura Petit   334.28

---
## PARTIE 8 â€” Grouper et Agreger

### groupby() : analyser par categories

`groupby()` est l'une des fonctions les plus puissantes de Pandas.

Elle permet de **regrouper** les lignes par categorie et de faire des **calculs** sur chaque groupe.

C'est comme demander : "Quel est le total des ventes PAR ville ?" ou "Quel est l'age moyen PAR region ?"

Etape 1 : On regroupe (groupby)
Etape 2 : On calcule (sum, mean, count...)

In [18]:
# Calcul du total des ventes par categorie de produit
# groupby("categorie") = regroupe toutes les lignes par categorie
# ["total"] = on s'interesse a la colonne total
# .sum() = on additionne le total de chaque groupe
ventes_par_categorie = df.groupby("categorie")["total"].sum()

print("Total des ventes par categorie :")
print(ventes_par_categorie.sort_values(ascending=False))

Total des ventes par categorie :
categorie
Périphérique    256865.56
Informatique     95560.60
Stockage         27349.17
Audio            21030.96
Accessoire       16455.77
Name: total, dtype: float64

In [19]:
# Calcul de la satisfaction moyenne par produit
satisfaction_par_produit = df.groupby("produit")["satisfaction"].mean()

print("Satisfaction moyenne par produit :")
print(satisfaction_par_produit.sort_values(ascending=False).head(10))

Satisfaction moyenne par produit :
produit
Tapis de Souris      3.666667
Clavier Mécanique    3.363636
Laptop Pro           3.333333
Disque SSD           3.222222
Écran 4K             3.200000
Souris Sans Fil      3.181818
Imprimante           3.000000
Hub USB              2.888889
Webcam HD            2.846154
Casque Audio         2.750000
Name: satisfaction, dtype: float64

In [20]:
# Plusieurs statistiques en meme temps avec .agg()
# agg = aggregate = agreger
stats_par_region = df.groupby("region")["total"].agg(
    total_ventes="sum",     # somme des ventes
    vente_moyenne="mean",   # moyenne
    nombre_ventes="count"   # nombre de ventes
)
print("Statistiques par region :")
print(stats_par_region.sort_values("total_ventes", ascending=False))

Statistiques par region :

                      total_ventes  vente_moyenne  nombre_ventes
region
PACA                     104958.53    9541.684545             11
Auvergne-Rhône-Alpes      90085.99    7507.165833             12
Île-de-France             54000.15    3600.010000             15
Afrique du Nord           30081.04    2148.645714             14
Canada                    26314.08    2631.408000             10
Afrique de l'Ouest        21422.60    2380.288889              9
Belgique                  11737.55    1676.792857              7

---
## PARTIE 9 â€” Fusionner des tableaux

### merge() et concat() : combiner des DataFrames

Parfois, les donnees sont reparties dans plusieurs fichiers.

- **`merge()`** : fusionne deux tableaux comme un LEFT JOIN SQL (par colonne commune)
- **`concat()`** : colle deux tableaux l'un au dessus de l'autre

In [21]:
# Exemple de merge : ajouter des informations supplementaires
# On cree un petit tableau avec des infos supplementaires par ville
infos_villes = pd.DataFrame({
    "ville": ["Paris", "Lyon", "Nice", "Bordeaux"],
    "population": [2161000, 515695, 342669, 254436],
    "region_officielle": ["Ile-de-France", "Auvergne-RA", "PACA", "Nouvelle-Aquitaine"]
})

# On fusionne : le tableau df + infos_villes, en les reliant par la colonne "ville"
df_enrichi = df.merge(infos_villes, on="ville", how="left")
# "left" = garder toutes les lignes de df, meme si pas de correspondance
print("DataFrame enrichi avec infos des villes :")
print(df_enrichi[["ville", "total", "population"]].head(5))

DataFrame enrichi avec infos des villes :
        ville    total  population
0       paris   559.00         NaN
1  Casablanca   210.64         NaN
2       Paris  2560.65   2161000.0
3       Paris  1032.84   2161000.0
4       paris  1642.30         NaN

In [22]:
# Exemple de concat : coller deux tableaux
# On cree deux sous-tableaux : ventes du premier et second semestre
df_S1 = df[df["date"] < "2024-07-01"].copy()  # avant juillet
df_S2 = df[df["date"] >= "2024-07-01"].copy() # apres juillet

# On les recolle avec concat
df_reconstitue = pd.concat([df_S1, df_S2], ignore_index=True)

print(f"S1 : {len(df_S1)} ventes")
print(f"S2 : {len(df_S2)} ventes")
print(f"Total reconstitue : {len(df_reconstitue)} ventes")

S1 : 54 ventes
S2 : 46 ventes
Total reconstitue : 100 ventes

---
## PARTIE 10 â€” Sauvegarder en CSV

### to_csv() : exporter les resultats

Apres avoir analyse et transforme les donnees, on peut sauvegarder le resultat dans un nouveau fichier CSV.

In [23]:
# On sauvegarde le top 20 des ventes dans un fichier CSV
top20_ventes = df.sort_values("total", ascending=False).head(20)

# to_csv() sauvegarde le DataFrame dans un fichier CSV
# index=False = ne pas ecrire le numero de ligne dans le fichier
top20_ventes.to_csv("top20_ventes.csv", index=False, encoding="utf-8")

print("Fichier top20_ventes.csv sauvegarde !")
print(f"Il contient {len(top20_ventes)} lignes")

Fichier top20_ventes.csv sauvegarde !
Il contient 20 lignes

---
## RECAPITULATIF DU MODULE 3

| Commande | Ce que ca fait |
|---------|----------------|
| `pd.read_csv("fichier.csv")` | Charge un CSV en DataFrame |
| `df.head()` | Affiche les 5 premieres lignes |
| `df.tail()` | Affiche les 5 dernieres lignes |
| `df.info()` | Infos sur les colonnes et les types |
| `df.describe()` | Statistiques des colonnes numeriques |
| `df.shape` | Taille (lignes, colonnes) |
| `df["col"]` | Selectionner une colonne |
| `df[["col1","col2"]]` | Selectionner plusieurs colonnes |
| `df.iloc[0]` | Selectionner par position |
| `df.loc[0, "col"]` | Selectionner par etiquette |
| `df[df["col"] > 100]` | Filtrer selon une condition |
| `df.sort_values("col")` | Trier selon une colonne |
| `df.groupby("col").sum()` | Grouper et agreger |
| `df.merge(df2, on="col")` | Fusionner deux tableaux |
| `pd.concat([df1, df2])` | Coller deux tableaux |
| `df.to_csv("fichier.csv")` | Sauvegarder en CSV |

**Dans le prochain module, on apprend a nettoyer les donnees â€” une etape indispensable avant toute analyse !**

---
---
# 📖 Ressources — Module 3 : Pandas

Pour aller plus loin sur Pandas, voici 3 ressources en français :

---

### 🔗 1. Introduction à Pandas – Python pour la data science — PythonDS (Lino Galiana)
**Lien :** https://pythonds.linogaliana.fr/content/manipulation/01_numpy.html

Excellente ressource académique française, très complète et rigoureuse.
Produite par un statisticien de l'INSEE — qualité professionnelle garantie.

---

### 🔗 2. Python Pandas - Tuto Partie 1 — DataCorner.fr
**Lien :** https://www.datacorner.fr/pandas-1/

Tutoriel en plusieurs parties, parfait pour une progression graduelle.
Les explications sont claires avec des exemples concrets proches de notre dataset.

---

### 🔗 3. Introduction à la bibliothèque Pandas — Developpez.com
**Lien :** https://python.developpez.com/tutoriels/introduction-bibliotheque-pandas/

Guide pas-à-pas avec exemples concrets, communauté francophone très active.
Bonne référence pour chercher de l'aide quand tu bloques.

---

> 💡 **Conseil :** Pandas est la bibliothèque que tu utiliseras le plus dans ta carrière. Prends le temps de maîtriser `groupby` et les filtres — ce sont les outils les plus puissants.

---
---
# 🎬 Vidéos YouTube — Pour aller plus loin

Ces 2 vidéos en français complètent parfaitement ce module. Regarde-les **après** avoir terminé le notebook pour consolider ce que tu as appris.

---

### 🎥 Vidéo 1 — Maîtriser Pandas Pour La Data Science En 20 min — Guide Complet Débutants

**Rechercher sur YouTube :** [Maîtriser Pandas Pour La Data Science En 20 min — Guide Complet Débutants](https://www.youtube.com/results?search_query=Ma%C3%AEtriser%20Pandas%20Pour%20La%20Data%20Science%20En%2020%20min%20%E2%80%94%20Guide%20Complet%20D%C3%A9butants)

DataFrames, filtres et groupby expliqués en 20 minutes chrono. Excellent résumé visuel de tout ce que tu viens d'apprendre — idéal après avoir fini le module.

---

### 🎥 Vidéo 2 — PANDAS PYTHON Français — Introduction + Analyse du Titanic

**Rechercher sur YouTube :** [PANDAS PYTHON Français — Introduction + Analyse du Titanic](https://www.youtube.com/results?search_query=PANDAS%20PYTHON%20Fran%C3%A7ais%20%E2%80%94%20Introduction%20%2B%20Analyse%20du%20Titanic)

Pandas mis en action sur le célèbre dataset Titanic. Voir Pandas appliqué à un vrai dataset différent du nôtre renforce beaucoup la compréhension.

---

> 💡 **Conseil :** Regarde d'abord le notebook en entier, fais les exercices, **puis** regarde les vidéos. Les vidéos servent à consolider, pas à remplacer la pratique.